language: node_js

node_js:
  - stable

cache:
  directories:
  - node_modules

before_deploy:
  - npm run build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: feature
