language: node_js

node_js:
  - stable

cache:
  directories:
  - node_modules

before_deploy:
  - npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  skip_cleanup: true
  local_dir: dist
  target_branch: master
  on:
    tags: true

notifications:
  email: false
  slack: $SLACK_TOKEN#cjpatoilogithubio
